### ISSUE TITLE
RangeError: Invalid status code: 0 at ServerResponse.writeHead (_http_server.js:192:11)

### ISSUE THREAD

**Issue by 009topersky** [IHTSDO/sct-snapshot-rest-api#31]
I Got this error !

RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at ServerResponse.writeHead (C:\Users\lenovo\Documents\SNOMED\mean\server\sct-snapshot-rest-api\node_modules\on-headers\index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:573:10)
    at ServerResponse.send (C:\Users\lenovo\Documents\SNOMED\mean\server\sct-snapshot-rest-api\node_modules\express\lib\response.js:211:10)
    at ServerResponse.json (C:\Users\lenovo\Documents\SNOMED\mean\server\sct-snapshot-rest-api\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (C:\Users\lenovo\Documents\SNOMED\mean\server\sct-snapshot-rest-api\node_modules\express\lib\response.js:158:21)
    at C:\Users\lenovo\Documents\SNOMED\mean\server\sct-snapshot-rest-api\app.js:104:33
    at Layer.handle_error (C:\Users\lenovo\Documents\SNOMED\mean\server\sct-snapshot-rest-api\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\lenovo\Documents\SNOMED\mean\server\sct-snapshot-rest-api\node_modules\express\lib\router\index.js:315:13)

**Comment by rorydavidson** [comment]
which version of node.js are you running?

**Comment by 009topersky** [comment]
node version **v6.11.4**

![image](https://user-images.githubusercontent.com/5698315/38192420-5d6b7548-369f-11e8-8d36-270781ad8308.png)

**Comment by rorydavidson** [comment]
Not sure where the error is coming from as it is working ok on ubuntu with node.js versions 5 and above. 

However, just completed a version using docker containers which you can find on the develop branch - https://github.com/IHTSDO/sct-snapshot-rest-api/tree/develop. This might bypass any issues that running node.js on Windows may be introducing.

**Comment by 009topersky** [comment]
Good day sir!

Currently i'm working on Windows 10 Environment

still i have the issue and i'm stuck :(

**Comment by 009topersky** [comment]
Moving forward.,

how can i get this version of **rf2-to-json-conversion**

https://github.com/IHTSDO/rf2-to-json-conversion

NOTE ensure you are using versions 1.3 and above of the conversion tool to create the JSON files. Older versions will not work.

**Comment by rorydavidson** [comment]
You can find it here  - https://github.com/IHTSDO/rf2-to-json-conversion/releases/tag/1.3

**Comment by mckanthcdoc** [comment]
Hi, I had this problem earlier as the status code was returning as text instead of code. You need to make changes to your app.js at 2 places i guess

In place of  (pls comment the below portion)
 /*res.send('error', {
        message: err.message,
        error: {}
    });*/
And change it to the below statement
res.status(err.status >= 100 && err.status < 600 ? err.code : 500).send(err.message);

This should work

**Comment by priyaranjan-tokachichu** [comment]
@rorydavidson , using the development branch, now I have the message from the server (RESTful API) "There are no data for this conceptId:<concept id present in the mongo db>". The concept id I was looking for is in the mongo db, but not returning a valid response from the server.
