### ISSUE TITLE
Issue with Retrieving Members

### ISSUE THREAD

**Issue by mckanthcdoc** [IHTSDO/sct-snapshot-rest-api#32]
I am unable to retrieve reference set members of a concept. Even with the reference URl https://snomedctsnapshotapi.docs.apiary.io/# i could see 502 Bad Gateway error.  is it a known issue

Regards,

**Comment by rorydavidson** [comment]
What is the full URL you are using, and which version of SNOMED CT have you loaded into the database?

**Comment by mckanthcdoc** [comment]
The reference is with a local host instance running with 20180131 version on MongoDB.
The URL is http://localhost:3000/snomed/en-edition/v20180131/concepts/721144007/members?limit=5&paginate=1

The same URL pattern works for descriptions, concepts, parent and child data fetches

Regards

**Comment by mckanthcdoc** [comment]
TypeError: Cannot read property 'refsets' of undefined
    at C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\lib\snomed.js:143:25
    at C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\lib\snomed.js:38:25
    at handleCallback (C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\node_modules\mongodb\lib\utils.js:120:56)
    at C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\node_modules\mongodb\lib\cursor.js:861:16
    at handleCallback (C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\node_modules\mongodb-core\lib\cursor.js:171:5)
    at setCursorNotified (C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\node_modules\mongodb-core\lib\cursor.js:515:3)
    at C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\node_modules\mongodb-core\lib\cursor.js:599:16
    at queryCallback (C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\node_modules\mongodb-core\lib\cursor.js:232:18)
    at C:\Users\mcsri\Desktop\SnoMed CT - RefSets\sct-snapshot-rest-api-master\node_modules\mongodb-core\lib\connection\pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Worker 10176 died with code: 1, and signal: null

**Comment by rorydavidson** [comment]
I'm not sure why you're getting that, but the repo has just been updated to the new v2, including docker config if you'd like to try that.
